<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="qsg-PC" name="requirementGroup.CreatingAndManagingUsers.NewForgotUserIDOrPasswordFunctionality" tests="3" failures="0" timestamp="6 Oct 2015 21:05:15 GMT" time="1003.594" errors="2">
  <testcase name="testHappyDay127893" time="293.183" classname="requirementGroup.CreatingAndManagingUsers.NewForgotUserIDOrPasswordFunctionality">
    <error type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at lib.page.MailVerificationFunctions.logoutMail(MailVerificationFunctions.java:271)
	at requirementGroup.CreatingAndManagingUsers.NewForgotUserIDOrPasswordFunctionality.testHappyDay127893(NewForgotUserIDOrPasswordFunctionality.java:280)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- testHappyDay127893 -->
  <testcase name="testHappyDay127884" time="428.658" classname="requirementGroup.CreatingAndManagingUsers.NewForgotUserIDOrPasswordFunctionality"/>
  <testcase name="testHappyDay127691" time="281.753" classname="requirementGroup.CreatingAndManagingUsers.NewForgotUserIDOrPasswordFunctionality">
    <error type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at lib.page.MailVerificationFunctions.logoutMail(MailVerificationFunctions.java:271)
	at requirementGroup.CreatingAndManagingUsers.NewForgotUserIDOrPasswordFunctionality.testHappyDay127691(NewForgotUserIDOrPasswordFunctionality.java:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- testHappyDay127691 -->
</testsuite> <!-- requirementGroup.CreatingAndManagingUsers.NewForgotUserIDOrPasswordFunctionality -->
